### PR TITLE
Update NLM URL

### PR DESCRIPTION
**Pull request by hacklschorsch**
New URL from https://knowledge.autodesk.com/search-result/caas/downloads/content/autodesk-network-license-manager-for-linux.html

### CODE REVIEW

**Comment by haysclark** [comment]
@hacklschorsch Thanks! I wonder if it's because they noticed some Docker image hot-linking the old one. Will verify and merge shortly.

**Comment by haysclark** [comment]
@hacklschorsch Are you at all blocked by this? If not, I was going to add some Automation before cutting another release. Additionally, when I authored this Docker image I wasn't expecting _nlm_ to change versions much, so I didn't put much thought into the Docker version numbers. I cut release 1.0 and thought I was good. Seeing the big change between _nlm11.13.1.2_ and _nlm11.16.2.0_ I'm wondering if I missed any other versions along the way.

Have any thoughts or input?

**Comment by haysclark** [comment]
@hacklschorsch Awesome! I just tested the service locally and it is backwards compatible (at least with Maya2014).

I will cut a build shortly, for version 1.0.1, as the Containers API has not changed.

Manual test log:
```
                                                                    
                                ##        .                         
                          ## ## ##       ==                         
                       ## ## ## ##      ===                         
                   /""""""""""""""""\\\___/ ===                     
              ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~                
                   \\______ o          __/                         
                     \\    \\        __/                          
                      \\____\\______/                             
                                                                    
  _   _           __  __ _    _      _    ___ _    _____  ___       
 | | | |_ _  ___ / _|/ _(_)__(_)__ _| |  | __| |  | __\ \/ / |_ __  
 | |_| | ' \/ _ \  _|  _| / _| / _` | |  | _|| |__| _| >  <| | '  \ 
  \___/|_||_\___/_| |_| |_\__|_\__,_|_|  |_| |____|___/_/\_\_|_|_|_|
    _  _     _                  _      ___                          
   | \| |___| |___ __ _____ _ _| |__  / __| ___ _ ___ _____ _ _     
   | .` / -_)  _\ V  V / _ \ '_| / /  \__ \/ -_) '_\ V / -_) '_|    
   |_|\_\___|\__|\_/\_/\___/_| |_\_\  |___/\___|_|  \_/\___|_|      
                                                                    
---------------------------------------------------------------------------
lmutil - Copyright (c) 1989-2018 Flexera. All Rights Reserved.
The FlexNet host ID of this machine is "[MAC_ADDRESS]"
---------------------------------------------------------------------------

18:29:14 (lmgrd) -----------------------------------------------
18:29:14 (lmgrd)   Please Note:
18:29:14 (lmgrd) 
18:29:14 (lmgrd)   This log is intended for debug purposes only.
18:29:14 (lmgrd)   In order to capture accurate license
18:29:14 (lmgrd)   usage data into an organized repository,
18:29:14 (lmgrd)   please enable report logging. Use Flexera's
18:29:14 (lmgrd)   software license administration  solution,
18:29:14 (lmgrd)   FlexNet Manager, to  readily gain visibility
18:29:14 (lmgrd)   into license usage data and to create
18:29:14 (lmgrd)   insightful reports on critical information like
18:29:14 (lmgrd)   license availability and usage. FlexNet Manager
18:29:14 (lmgrd)   can be fully automated to run these reports on
18:29:14 (lmgrd)   schedule and can be used to track license
18:29:14 (lmgrd)   servers and usage across a heterogeneous
18:29:14 (lmgrd)   network of servers including Windows NT, Linux
18:29:14 (lmgrd)   and UNIX.
18:29:14 (lmgrd) 
18:29:14 (lmgrd) -----------------------------------------------
18:29:14 (lmgrd) 
18:29:14 (lmgrd) 
18:29:14 (lmgrd) Server's System Date and Time: Thu Jan 30 2020 18:29:14 UTC
18:29:14 (lmgrd) SLOG: Summary LOG statistics is enabled.
18:29:15 (lmgrd) FlexNet Licensing (v11.16.2.0 build 242433 x64_lsb) started on [ServerHostname] (linux) (1/30/2020)
18:29:15 (lmgrd) Copyright (c) 1988-2018 Flexera. All Rights Reserved.
18:29:15 (lmgrd) World Wide Web:  http://www.flexerasoftware.com
18:29:15 (lmgrd) License file(s): /var/flexlm/mayaserver.lic
18:29:15 (lmgrd) lmgrd tcp-port 27000
18:29:15 (lmgrd) (@lmgrd-SLOG@) ===============================================
18:29:15 (lmgrd) (@lmgrd-SLOG@) === LMGRD ===
18:29:15 (lmgrd) (@lmgrd-SLOG@) Start-Date: Thu Jan 30 2020 18:29:15 UTC
18:29:15 (lmgrd) (@lmgrd-SLOG@) PID: 7
18:29:15 (lmgrd) (@lmgrd-SLOG@) LMGRD Version: v11.16.2.0 build 242433 x64_lsb ( build 242433 (ipv6))
18:29:15 (lmgrd) (@lmgrd-SLOG@) 
18:29:15 (lmgrd) (@lmgrd-SLOG@) === Network Info ===
18:29:15 (lmgrd) (@lmgrd-SLOG@) Listening port: 27000
18:29:15 (lmgrd) (@lmgrd-SLOG@) 
18:29:15 (lmgrd) (@lmgrd-SLOG@) === Startup Info ===
18:29:15 (lmgrd) (@lmgrd-SLOG@) Server Configuration: Single Server
18:29:15 (lmgrd) (@lmgrd-SLOG@) Command-line options used at LS startup: -z -c /var/flexlm/mayaserver.lic 
18:29:15 (lmgrd) (@lmgrd-SLOG@) License file(s) used:  /var/flexlm/mayaserver.lic
18:29:15 (lmgrd) (@lmgrd-SLOG@) ===============================================
18:29:15 (lmgrd) Starting vendor daemons ... 
18:29:15 (lmgrd) Starting vendor daemon at port 2080
18:29:15 (lmgrd) Using vendor daemon port 2080 specified in license file
18:29:15 (lmgrd) Started adskflex (internet tcp_port 2080 pid 9)
18:29:15 (adskflex) Unable to initialize access to trusted storage: 2
18:29:15 (adskflex) FlexNet Licensing version v11.16.2.0 build 242433 x64_lsb
18:29:15 (adskflex) SLOG: Summary LOG statistics is enabled.
18:29:15 (adskflex) SLOG: FNPLS-INTERNAL-CKPT1
18:29:15 (adskflex) SLOG: VM Status: 4
18:29:15 (adskflex) SLOG: FNPLS-INTERNAL-CKPT5
18:29:15 (adskflex) SLOG: TPM Status: 0
18:29:15 (adskflex) SLOG: FNPLS-INTERNAL-CKPT6
18:29:15 (adskflex) Server started on [ServerHostname] for:	86058MAYA_2014_0F 
18:29:15 (adskflex) 86058MAYAMMR1_2014_0F 86095TRTLPB_2014_0F 
18:29:15 (adskflex) EXTERNAL FILTERS are OFF
18:29:15 (lmgrd) adskflex using TCP-port 2080
18:29:15 (adskflex) SLOG: Statistics Log Frequency is 240 minute(s).
18:29:15 (adskflex) SLOG: TS update poll interval is 600 seconds.
18:29:15 (adskflex) SLOG: Activation borrow reclaim percentage is 0.
18:29:15 (adskflex) (@adskflex-SLOG@) ===============================================
18:29:15 (adskflex) (@adskflex-SLOG@) === Vendor Daemon ===
18:29:15 (adskflex) (@adskflex-SLOG@) Vendor daemon: adskflex
18:29:15 (adskflex) (@adskflex-SLOG@) Start-Date: Thu Jan 30 2020 18:29:15 UTC
18:29:15 (adskflex) (@adskflex-SLOG@) PID: 9
18:29:15 (adskflex) (@adskflex-SLOG@) VD Version: v11.16.2.0 build 242433 x64_lsb ( build 242433 (ipv6))
18:29:15 (adskflex) (@adskflex-SLOG@) 
18:29:15 (adskflex) (@adskflex-SLOG@) === Startup/Restart Info ===
18:29:15 (adskflex) (@adskflex-SLOG@) Options file used: None
18:29:15 (adskflex) (@adskflex-SLOG@) Is vendor daemon a CVD: No
18:29:15 (adskflex) (@adskflex-SLOG@) Is FlexNet Licensing Service installed and compatible: No
18:29:15 (adskflex) (@adskflex-SLOG@) FlexNet Licensing Service Version: -NA-
18:29:15 (adskflex) (@adskflex-SLOG@) Is TS accessed: No
18:29:15 (adskflex) (@adskflex-SLOG@) TS access time: -NA-
18:29:15 (adskflex) (@adskflex-SLOG@) Number of VD restarts since LS startup: 0
18:29:15 (adskflex) (@adskflex-SLOG@) 
18:29:15 (adskflex) (@adskflex-SLOG@) === Network Info ===
18:29:15 (adskflex) (@adskflex-SLOG@) Listening port: 2080
18:29:15 (adskflex) (@adskflex-SLOG@) Daemon select timeout (in seconds): 1
18:29:15 (adskflex) (@adskflex-SLOG@) 
18:29:15 (adskflex) (@adskflex-SLOG@) === Host Info ===
18:29:15 (adskflex) (@adskflex-SLOG@) Host used in license file: [ServerHostname]
18:29:15 (adskflex) (@adskflex-SLOG@) HostID node-locked in license file: [MAC_ADDRESS] 
18:29:15 (adskflex) (@adskflex-SLOG@) HostID of the License Server: [MAC_ADDRESS]
18:29:15 (adskflex) (@adskflex-SLOG@) Running on Hypervisor: Unknown Hypervisor
18:29:15 (adskflex) (@adskflex-SLOG@) ===============================================
18:29:53 (adskflex) TCP_NODELAY NOT enabled
18:29:53 (adskflex) OUT: "86058MAYA_2014_0F" [User@Hostname]  
18:30:07 (adskflex) IN: "86058MAYA_2014_0F" [User@Hostname]  
```

**Comment by haysclark** [comment]
@hacklschorsch Thanks again for the contribution!

**Comment by hacklschorsch** [comment]
Hi!

> I wonder if it's because they noticed some Docker image hot-linking the old one. Will verify and merge shortly.

Don't think so, why should they. Both the old and the new link work.

> Are you at all blocked by this?

No, chill! Thank you!

> Have any thoughts or input?

I just thought updating makes sense - it's a network service after all, and it was easy to do.

Thank you for your consideration and swift reply!

**Pull request merged**
